# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
  theme:
    _target_: lightning.pytorch.callbacks.progress.rich_progress.RichProgressBarTheme
    metrics_format: ".3e"
